import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from './componentes/button';
import CardGroup from './componentes/cardGroup';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Actividad Clase Nº10</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        Hello world
      
        <br></br>
        <Button></Button>
        <div className='cardgroup'>
            <CardGroup />
        </div>
      </main>
    </>
  )
}

